# Generated by Django 5.1.7 on 2025-03-12 00:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nro_matricula', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidades', models.ManyToManyField(blank=True, to='turnosApp.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_turno', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('nro_seguro', models.CharField(max_length=20)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='turnosApp.medicos')),
            ],
        ),
    ]
