# Generated by Django 5.1.7 on 2025-03-12 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnos',
            name='medico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='turnosApp.medicos'),
        ),
    ]
