# Generated by Django 5.1.7 on 2025-03-12 21:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0002_turnos_id_alter_turnos_medico'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidad',
        ),
        migrations.RenameModel(
            old_name='Medicos',
            new_name='Medico',
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_turno', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('nro_seguro', models.CharField(max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnosApp.medico')),
            ],
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
