# Generated by Django 5.1.7 on 2025-03-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0003_rename_especialidades_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
