# Generated by Django 5.1.7 on 2025-03-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0004_turno_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='nro_telefono',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
