# Generated by Django 5.1.7 on 2025-03-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0005_turno_ciudad_turno_nro_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
