# Generated by Django 5.1.7 on 2025-03-28 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0007_turno_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='ci',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nro_seguro',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='nro_telefono',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='sexo',
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('conacto', models.CharField(max_length=100)),
                ('tipo_contacto', models.BooleanField(default=False)),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnosApp.sexo')),
            ],
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turnosApp.paciente'),
            preserve_default=False,
        ),
    ]
