# Generated by Django 5.1.7 on 2025-03-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0008_remove_turno_ci_remove_turno_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turno',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
