# Generated by Django 5.1.7 on 2025-03-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0009_paciente_status_turno_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
